### ISSUE TITLE
sampling (-i option) in RNAshapes

### ISSUE THREAD

**Issue by HarveyYan** [dmaticzka/GraphProt#4]
Hello, I see that you have a sampling option which is not mentioned in your paper, and I'm having problems to understand why you need to do that. Since you are only taking 3 shreps, why not just the 3 with the lowest free energy, or the 3 with the highest shape probabilities (neither requires sampling)? Could you explain the comments on line 821&822 in fasta2shrep_gspan.pl? Thanks a lot.

**Comment by dmaticzka** [comment]
Dear HarveyYan, the sampling option of fasta2shrep_gspan.pl is not used by GraphProt. fasta2shrep_gspan.pl is a general-purpose script also used by other projects. Best, Daniel
