### ISSUE TITLE
Trouble installing graphprot on conda

### ISSUE THREAD

**Issue by keenhl** [dmaticzka/GraphProt#7]
I tried to install graphprot via conda, but get the below error. Thanks for your help.

##

conda install graphprot

##

Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - graphprot

Current channels:

  - https://conda.anaconda.org/bioconda
  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by dmaticzka** [comment]
GraphProt is not available for conda osx-64. Maybe the docker image built from the conda package could be useful to you:
```
docker pull quay.io/biocontainers/graphprot:1.1.7--2
```
